# Generated by Django 6.1 on 2026-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_options_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
