[project]
name = "pythonproject5"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.14"
dependencies = [
    "python (>=3.14,<4.0)",
    "django (>=6.1,<7.0)",
    "djangorestframework (>=3.18.0,<4.0.0)",
    "psycopg (>=3.3.4,<4.0.0)",
    "pillow (>=12.3.0,<13.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "django-filter (>=26.1,<27.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "ipython (>=9.16.1,<10.0.0)",
    "coverage (>=7.16.0,<8.0.0)",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "stripe (>=15.6.1,<16.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
