# Generated by Django 6.1 on 2026-08-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblearn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="learn_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="weblearn.learncourse",
                verbose_name="Курс",
            ),
        ),
    ]
