# Generated by Django 6.1 on 2026-08-31 17:44

import weblearn.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblearn", "0004_alter_learncourse_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(validators=[weblearn.validators.LessonLinkValidator]),
        ),
    ]
