# Generated by Django 6.1 on 2026-08-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblearn", "0005_alter_lesson_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(),
        ),
    ]
